export const MUSIC_APP_KEYPRESS = 'MUSIC_APP_KEYPRESS';
export const MUSIC_APP_KEYPRESSED = 'MUSIC_APP_KEYPRESSED';
export const MUSIC_APP_KEYDEPRESSED = 'MUSIC_APP_KEYDEPRESSED';
export const MUSIC_APP_KEYUP = 'MUSIC_APP_KEYUP';
export const MUSIC_APP_KEY_ACTIVATE = 'MUSIC_APP_KEY_ACTIVATE';
export const MUSIC_APP_KEY_DEACTIVATE = 'MUSIC_APP_KEY_DEACTIVATE';