export const MUSIC_APP_KEYDOWN = 'MUSIC_APP_KEYDOWN';
export const MUSIC_APP_KEYUP = 'MUSIC_APP_KEYUP';
export const MUSIC_APP_KEY_ACTIVATE = 'MUSIC_APP_KEY_ACTIVATE';
export const MUSIC_APP_KEY_DEACTIVATE = 'MUSIC_APP_KEY_DEACTIVATE';
export const MUSIC_APP_KEY_ADD_BUFFER = 'MUSIC_APP_KEY_ADD_BUFFER';
export const MUSIC_APP_KEY_UPDATE_STEP = 'MUSIC_APP_KEY_UPDATE_STEP';

export const SOUNDBANK_SHOW = 'SOUNDBANK_SHOW';
export const SOUNDBANK_CLOSE = 'SOUNDBANK_CLOSE';
export const SOUNDBANK_CANCEL = 'SOUNDBANK_CANCEL';

export const METRONOME_STOP = 'METRONOME_STOP';
export const METRONOME_PLAY = 'METRONOME_PLAY';
export const METRONOME_BPM_UPDATE = 'METRONOME_BPM_UPDATE';
