const keyList = [
  { keyCode: 192, key: '`', },
  { keyCode: 49, key: '1', },
  { keyCode: 50, key: '2', },
  { keyCode: 51, key: '3', },
  { keyCode: 52, key: '4', },
  { keyCode: 53, key: '5', },
  { keyCode: 54, key: '6', },
  { keyCode: 55, key: '7', },
  { keyCode: 56, key: '8', },
  { keyCode: 57, key: '9', },
  { keyCode: 48, key: '0', },
  { keyCode: 189, key: '-', },
  { keyCode: 187, key: '=', },
  { keyCode: 81, key: 'q', },
  { keyCode: 87, key: 'w', },
  { keyCode: 69, key: 'e', },
  { keyCode: 82, key: 'r', },
  { keyCode: 84, key: 't', },
  { keyCode: 89, key: 'y', },
  { keyCode: 85, key: 'u', },
  { keyCode: 73, key: 'i', },
  { keyCode: 79, key: 'o', },
  { keyCode: 80, key: 'p', },
  { keyCode: 219, key: '[', },
  { keyCode: 221, key: ']', },
  { keyCode: 220, key: '\\', },
  { keyCode: 65, key: 'a', },
  { keyCode: 83, key: 's', },
  { keyCode: 68, key: 'd', },
  { keyCode: 70, key: 'f', },
  { keyCode: 71, key: 'g', },
  { keyCode: 72, key: 'h', },
  { keyCode: 74, key: 'j', },
  { keyCode: 75, key: 'k', },
  { keyCode: 76, key: 'l', },
  { keyCode: 186, key: ';', },
  { keyCode: 222, key: '\'', },
  { keyCode: 90, key: 'z', },
  { keyCode: 88, key: 'x', },
  { keyCode: 67, key: 'c', },
  { keyCode: 86, key: 'v', },
  { keyCode: 66, key: 'b', },
  { keyCode: 78, key: 'n', },
  { keyCode: 77, key: 'm', },
  { keyCode: 188, key: ',', },
  { keyCode: 190, key: '.', },
  { keyCode: 191, key: '/', }
];
const keyMap = keyList.map(key => ({
  active: false,
  ...key,
  steps: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  ratio: 16,
  playbackRate: 1,
  buffer: undefined,
  channelInput: undefined,
  channelOutput: undefined,
  gain: 1,
  bass: 1,
  mid: 1,
  tre: 1,
  pan: 0,
  filterList: [
    { type: 'delay', bypass: false },
    { type: 'phaser', bypass: false }
  ]
}));

export default keyMap;
